"""add universe screening and sector models

Revision ID: 83a14d86fc84
Revises: 82dd4da97f84
Create Date: 2026-02-23 11:54:48.044600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a14d86fc84'
down_revision: Union[str, None] = '82dd4da97f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_universe',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_stock_universe_sector'), 'stock_universe', ['sector'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('volume_avg', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('screened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_results_simulation_id'), 'screening_results', ['simulation_id'], unique=False)
    op.create_table('sector_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_models_sector'), 'sector_models', ['sector'], unique=False)
    op.add_column('price_data', sa.Column('fetched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_data', 'fetched_at')
    op.drop_index(op.f('ix_sector_models_sector'), table_name='sector_models')
    op.drop_table('sector_models')
    op.drop_index(op.f('ix_screening_results_simulation_id'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_stock_universe_sector'), table_name='stock_universe')
    op.drop_table('stock_universe')
    # ### end Alembic commands ###
